package com.foodies.freshmeal.order.dto;

import java.io.Serial;
import java.io.Serializable;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * ============================================================================
 * DTO : OrderStatusUpdateRequest
 * ============================================================================
 *
 * Represents a request to change the current business status of an order.
 *
 * <p>
 * This DTO intentionally contains only information required to request a
 * lifecycle status transition.
 * </p>
 *
 * <p>
 * The requested status is represented as a String at the API boundary.
 * The service layer is responsible for converting it into
 * {@code OrderStatusConstant} and validating whether the requested transition
 * is permitted.
 * </p>
 *
 * <p>
 * The request does not contain:
 * </p>
 *
 * <ul>
 * <li>Order identifier - supplied through the service input/path context.</li>
 * <li>Current status - loaded from the OrderEntity.</li>
 * <li>Updated by - resolved from IServiceContext.</li>
 * <li>Updated timestamp - generated by the service/domain layer.</li>
 * </ul>
 *
 * ============================================================================
 *
 * Example
 * -------
 *
 * {
 * "status": "CONFIRMED",
 * "reason": "Restaurant accepted the order",
 * "remarks": "Kitchen notified"
 * }
 *
 * ============================================================================
 *
 * @author Pankaj Kumar
 * @since 1.0
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderStatusUpdateRequest implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    // =========================================================================
    // Status
    // =========================================================================

    /**
     * Requested target Order status.
     *
     * <p>
     * Example:
     * </p>
     *
     * <ul>
     * <li>CONFIRMED</li>
     * <li>PREPARING</li>
     * <li>READY_FOR_PICKUP</li>
     * <li>DELIVERED</li>
     * </ul>
     *
     * <p>
     * The service layer converts this value to
     * {@code OrderStatusConstant} and validates the lifecycle transition.
     * </p>
     */
    @NotBlank(message = "Order status is required.")
    private String status;

    // =========================================================================
    // Reason
    // =========================================================================

    /**
     * Business reason associated with the requested status change.
     *
     * <p>
     * Particularly useful for exceptional or administrative transitions.
     * </p>
     */
    @Size(max = 500, message = "Reason cannot exceed 500 characters.")
    private String reason;

    // =========================================================================
    // Remarks
    // =========================================================================

    /**
     * Additional administrative remarks associated with the status change.
     */
    @Size(max = 1000, message = "Remarks cannot exceed 1000 characters.")
    private String remarks;

}