spring.application.name=freshmeal


# Mongo DB configurations
spring.data.mongodb.url = mongodb://localhost:27017/meal

#AWS S3 configuration from environment variables 
aws.access.key = ${ACCESS_KEY}
aws.secret.key = ${SECRET_KEY}
aws.region = ap-south-1

# =====================================================
# MONGO QUERY LOGGING
# =====================================================

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

logging.level.org.mongodb.driver.protocol.command=TRACE


# =====================================================
# APPLICATION LOGGING
# =====================================================

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


