spring.application.name=freshmeal


# Mongo DB configurations
spring.data.mongodb.url = mongodb://localhost:27017/meal

#AWS S3 configuration from environment variables 
aws.access.key = ${ACCESS_KEY}
aws.secret.key = ${SECRET_KEY}
aws.region = ap-south-1
