
package com.foodies.freshmeal.checkout.valueObject;

import java.io.Serial;
import java.io.Serializable;

import com.foodies.freshmeal.common.valueObject.Money;
import com.foodies.freshmeal.image.dto.ImageSnapshot;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Represents an immutable-in-practice snapshot of a food item included
 * in a checkout session.
 *
 * <p>
 * The snapshot preserves the food information and pricing reviewed
 * by the customer at checkout initiation or validation.
 * </p>
 *
 * <p>
 * It is independent of subsequent changes to the original food
 * document. The Checkout service is responsible for creating and
 * refreshing this snapshot after validating the current food data.
 * </p>
 *
 * <p>
 * All monetary values must be calculated by the backend. Clients
 * must not be allowed to supply or modify snapshot prices directly.
 * </p>
 *
 * @author Pankaj Kumar
 */
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CheckoutItemSnapshot implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Unique business identifier of the food item.
     */
    private String foodNumber;

    /**
     * Food name captured at the time of checkout review.
     */
    private String foodName;

    /**
     * Image information captured for display purposes.
     */
    private ImageSnapshot foodImage;

    /**
     * Unit price validated by the backend.
     */
    private Money unitPrice;

    /**
     * Quantity selected by the customer.
     */
    private int quantity;

    /**
     * Total amount for this item, calculated as unit price multiplied
     * by quantity.
     *
     * <p>
     * This value is generated by the backend and must remain
     * consistent with the unit price and quantity.
     * </p>
     */
    private Money itemTotal;
}