package com.foodies.freshmeal.order.constants;

import com.foodies.freshmeal.common.contract.IDisplayOption;

/**
 * ============================================================================
 * Enum : CancellationReasonConstant
 * ============================================================================
 *
 * Represents the business reason associated with an order cancellation.
 *
 * Cancellation reasons are grouped according to the actor or business area
 * responsible for the cancellation.
 *
 * This enum is a classification and therefore does not represent a lifecycle
 * state machine.
 *
 * ============================================================================
 *
 * CUSTOMER
 * --------
 *
 * Reasons initiated by the customer.
 *
 * CUSTOMER_CHANGED_MIND
 * ORDERED_BY_MISTAKE
 * DUPLICATE_ORDER
 * FOUND_BETTER_PRICE
 * WRONG_DELIVERY_ADDRESS
 * PAYMENT_ISSUE
 *
 * ============================================================================
 *
 * RESTAURANT
 * ----------
 *
 * Reasons originating from the restaurant.
 *
 * RESTAURANT_CLOSED
 * ITEM_OUT_OF_STOCK
 * RESTAURANT_UNAVAILABLE
 * RESTAURANT_REJECTED_ORDER
 * HIGH_ORDER_VOLUME
 *
 * ============================================================================
 *
 * DELIVERY
 * --------
 *
 * Reasons related to delivery fulfillment.
 *
 * DELIVERY_PARTNER_UNAVAILABLE
 * DELIVERY_DELAY
 * DELIVERY_ADDRESS_NOT_SERVICEABLE
 *
 * ============================================================================
 *
 * SYSTEM
 * ------
 *
 * Reasons generated by automated system/business rules.
 *
 * TECHNICAL_ISSUE
 * FRAUD_DETECTED
 * ORDER_EXPIRED
 * PAYMENT_TIMEOUT
 *
 * ============================================================================
 *
 * ADMIN
 * -----
 *
 * Administrative cancellation.
 *
 * ADMIN_CANCELLED
 * OTHER
 *
 * ============================================================================
 */
public enum CancellationReasonConstant implements IDisplayOption {

    // =========================================================================
    // CUSTOMER
    // =========================================================================

    CUSTOMER_CHANGED_MIND("Customer Changed Mind"),

    ORDERED_BY_MISTAKE("Ordered By Mistake"),

    DUPLICATE_ORDER("Duplicate Order"),

    FOUND_BETTER_PRICE("Found Better Price"),

    WRONG_DELIVERY_ADDRESS("Wrong Delivery Address"),

    PAYMENT_ISSUE("Payment Issue"),

    // =========================================================================
    // RESTAURANT
    // =========================================================================

    RESTAURANT_CLOSED("Restaurant Closed"),

    ITEM_OUT_OF_STOCK("Item Out Of Stock"),

    RESTAURANT_UNAVAILABLE("Restaurant Unavailable"),

    RESTAURANT_REJECTED_ORDER("Restaurant Rejected Order"),

    HIGH_ORDER_VOLUME("High Order Volume"),

    // =========================================================================
    // DELIVERY
    // =========================================================================

    DELIVERY_PARTNER_UNAVAILABLE("Delivery Partner Unavailable"),

    DELIVERY_DELAY("Delivery Delay"),

    DELIVERY_ADDRESS_NOT_SERVICEABLE("Delivery Address Not Serviceable"),

    // =========================================================================
    // SYSTEM
    // =========================================================================

    TECHNICAL_ISSUE("Technical Issue"),

    FRAUD_DETECTED("Fraud Detected"),

    ORDER_EXPIRED("Order Expired"),

    PAYMENT_TIMEOUT("Payment Timeout"),

    // =========================================================================
    // ADMIN
    // =========================================================================

    ADMIN_CANCELLED("Cancelled By Admin"),

    OTHER("Other");

    /**
     * User-friendly display label.
     */
    private final String displayName;

    /**
     * Creates a cancellation reason.
     *
     * @param displayName user-friendly display label
     */
    CancellationReasonConstant(String displayName) {
        this.displayName = displayName;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLabel() {
        return displayName;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getValue() {
        return name();
    }
}