package com.foodies.freshmeal.common.exception;

import java.io.IOException;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.HttpMessageNotReadableException;
import org.springframework.messaging.handler.annotation.support.MethodArgumentNotValidException;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.AuthenticationException;
import org.springframework.web.HttpRequestMethodNotSupportedException;
import org.springframework.web.bind.MissingPathVariableException;
import org.springframework.web.bind.MissingRequestHeaderException;
import org.springframework.web.bind.MissingServletRequestParameterException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException;
import org.springframework.web.multipart.MaxUploadSizeExceededException;
import org.springframework.web.multipart.MultipartException;
import org.springframework.web.servlet.NoHandlerFoundException;

import com.foodies.freshmeal.common.builder.ApiResponseBuilder;
import com.foodies.freshmeal.common.constants.ErrorCodeConstants;
import com.foodies.freshmeal.common.constants.HttpStatusCode;
import com.foodies.freshmeal.common.dto.ApiResponse;
import com.mongodb.MongoException;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.ConstraintViolationException;

/**
 * ===========================================================
 * Global Exception Handler
 * ===========================================================
 *
 * <p>
 * Centralized exception handling component responsible for converting
 * application, framework and system exceptions into a consistent
 * {@link com.foodies.freshmeal.common.dto.ApiResponse}.
 * </p>
 *
 * <p>
 * Responsibilities:
 * <ul>
 * <li>Handle business exceptions.</li>
 * <li>Handle validation failures.</li>
 * <li>Handle request parsing errors.</li>
 * <li>Handle authentication and authorization errors.</li>
 * <li>Handle file upload exceptions.</li>
 * <li>Handle database exceptions.</li>
 * <li>Handle unexpected system exceptions.</li>
 * </ul>
 * </p>
 *
 * <p>
 * Every exception is logged before an appropriate response is returned to the
 * client.
 * </p>
 *
 * @author Pankaj
 * @since 1.0
 */
@RestControllerAdvice
public class GlobalExceptionHandler {

    /**
     * Logger.
     */
    private static final Logger LOGGER = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    // ===========================================================
    // Validation Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Business
     * Validation Exception
     * ===========================================================
     *
     * <p>
     * Handles validation failures generated by application validators.
     * </p>
     *
     * @param exception Validation exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(ValidationException.class)
    public ResponseEntity<ApiResponse<Void>> handleValidationException(ValidationException exception) {

        LOGGER.warn("Validation failed : {}", exception.getMessage());

        List<String> errors = exception.getValidationResult().getErrors().stream()
                .map(error -> error.getMessage())
                .toList();

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), exception.getMessage(), errors);
    }

    /**
     * =========================================================== Handle Method
     * Argument Validation Exception
     * ===========================================================
     *
     * Handles Bean Validation (@Valid) failures.
     *
     * @param exception Validation exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiResponse<Void>> handleMethodArgumentNotValidException(
            MethodArgumentNotValidException exception) {

        LOGGER.warn("Bean validation failed.");

        List<String> errors = exception.getBindingResult().getFieldErrors().stream()
                .map(fieldError -> fieldError.getDefaultMessage())
                .toList();

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Validation failed.", errors);
    }

    /**
     * =========================================================== Handle Constraint
     * Violation Exception
     * ===========================================================
     *
     * Handles validation failures for path variables and request parameters.
     *
     * @param exception Constraint violation exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(ConstraintViolationException.class)
    public ResponseEntity<ApiResponse<Void>> handleConstraintViolationException(
            ConstraintViolationException exception) {

        LOGGER.warn("Constraint validation failed.");

        List<String> errors = exception.getConstraintViolations().stream()
                .map((ConstraintViolation<?> violation) -> violation.getMessage())
                .toList();

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Validation failed.", errors);
    }

    // ===========================================================
    // Business Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Business
     * Exception ===========================================================
     *
     * Handles generic business rule violations.
     *
     * @param exception Business exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(BusinessException.class)
    public ResponseEntity<ApiResponse<Void>> handleBusinessException(BusinessException exception) {

        LOGGER.warn("Business exception occurred : {}", exception.getMessage());

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), exception.getMessage(),
                List.of(exception.getMessage()));
    }

    /**
     * =========================================================== Handle Resource
     * Not Found Exception
     * ===========================================================
     *
     * Handles requests where the requested resource does not exist.
     *
     * @param exception Resource not found exception
     *
     * @return HTTP 404 Not Found response
     */
    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<ApiResponse<Void>> handleResourceNotFoundException(ResourceNotFoundException exception) {

        LOGGER.warn("Resource not found : {}", exception.getMessage());

        return ApiResponseBuilder.notFound(ErrorCodeConstants.FM_AUTH_003 , exception.getMessage());
    }

    /**
     * =========================================================== Handle Duplicate
     * Resource Exception
     * ===========================================================
     *
     * Handles duplicate resource creation requests.
     *
     * @param exception Duplicate resource exception
     *
     * @return HTTP 409 Conflict response
     */
    @ExceptionHandler(DuplicateResourceException.class)
    public ResponseEntity<ApiResponse<Void>> handleDuplicateResourceException(DuplicateResourceException exception) {

        LOGGER.warn("Duplicate resource : {}", exception.getMessage());

        return ApiResponseBuilder.conflict(ErrorCodeConstants.FM_COM_004 , exception.getMessage());
    }

    /**
     * =========================================================== Handle Illegal
     * Argument Exception
     * ===========================================================
     *
     * Handles invalid method arguments.
     *
     * @param exception Illegal argument exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ApiResponse<Void>> handleIllegalArgumentException(IllegalArgumentException exception) {

        LOGGER.warn("Illegal argument : {}", exception.getMessage());

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), exception.getMessage(),
                List.of(exception.getMessage()));
    }

    /**
     * =========================================================== Handle Illegal
     * State Exception ===========================================================
     *
     * Handles invalid application state.
     *
     * @param exception Illegal state exception
     *
     * @return HTTP 409 Conflict response
     */
    @ExceptionHandler(IllegalStateException.class)
    public ResponseEntity<ApiResponse<Void>> handleIllegalStateException(IllegalStateException exception) {

        LOGGER.warn("Illegal state : {}", exception.getMessage());

        return ApiResponseBuilder.conflict(ErrorCodeConstants.FM_COM_004 , exception.getMessage());
    }

    // ===========================================================
    // Authentication & Authorization Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle
     * Unauthorized Exception
     * ===========================================================
     *
     * Handles authentication failures where the client has not been authenticated
     * successfully.
     *
     * @param exception Unauthorized exception
     *
     * @return HTTP 401 Unauthorized response
     */
    @ExceptionHandler(UnauthorizedException.class)
    public ResponseEntity<ApiResponse<Void>> handleUnauthorizedException(UnauthorizedException exception) {

        LOGGER.warn("Unauthorized access : {}", exception.getMessage());

        return ApiResponseBuilder.unauthorized(ErrorCodeConstants.FM_AUTH_002 , exception.getMessage());
    }

    /**
     * =========================================================== Handle Forbidden
     * Exception ===========================================================
     *
     * Handles requests where the authenticated user does not have permission to
     * access the requested resource.
     *
     * @param exception Forbidden exception
     *
     * @return HTTP 403 Forbidden response
     */
    @ExceptionHandler(ForbiddenException.class)
    public ResponseEntity<ApiResponse<Void>> handleForbiddenException(ForbiddenException exception) {

        LOGGER.warn("Access denied : {}", exception.getMessage());

        return ApiResponseBuilder.forbidden(ErrorCodeConstants.FM_AUTH_001 , exception.getMessage());
    }

    /**
     * =========================================================== Handle Spring
     * Access Denied Exception
     * ===========================================================
     *
     * Handles authorization failures generated by Spring Security.
     *
     * @param exception Access denied exception
     *
     * @return HTTP 403 Forbidden response
     */
    @ExceptionHandler(AccessDeniedException.class)
    public ResponseEntity<ApiResponse<Void>> handleAccessDeniedException(AccessDeniedException exception) {

        LOGGER.warn("Spring Security access denied : {}", exception.getMessage());

        return ApiResponseBuilder.forbidden(ErrorCodeConstants.FM_AUTH_003 , "Access denied.");
    }

    /**
     * =========================================================== Handle Spring
     * Authentication Exception
     * ===========================================================
     *
     * Handles authentication failures generated by Spring Security.
     *
     * @param exception Authentication exception
     *
     * @return HTTP 401 Unauthorized response
     */
    @ExceptionHandler(AuthenticationException.class)
    public ResponseEntity<ApiResponse<Void>> handleAuthenticationException(AuthenticationException exception) {

        LOGGER.warn("Authentication failed : {}", exception.getMessage());

        return ApiResponseBuilder.unauthorized(ErrorCodeConstants.FM_AUTH_002 , "Authentication failed.");
    }

    // ===========================================================
    // Request Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle
     * HttpMessageNotReadableException
     * ===========================================================
     *
     * Handles malformed JSON requests, invalid enum values, invalid date formats
     * and unreadable request bodies.
     *
     * @param exception HTTP message not readable exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(HttpMessageNotReadableException.class)
    public ResponseEntity<ApiResponse<Void>> handleHttpMessageNotReadableException(
            HttpMessageNotReadableException exception) {

        LOGGER.warn("Malformed request body : {}", exception.getMessage());

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Invalid request payload.",
                List.of("Request body is malformed or contains invalid values."));
    }

    /**
     * =========================================================== Handle Missing
     * Request Parameter Exception
     * ===========================================================
     *
     * Handles missing query parameters.
     *
     * @param exception Missing request parameter exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MissingServletRequestParameterException.class)
    public ResponseEntity<ApiResponse<Void>> handleMissingServletRequestParameterException(
            MissingServletRequestParameterException exception) {

        LOGGER.warn("Missing request parameter : {}", exception.getParameterName());

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Missing request parameter.",
                List.of("Required parameter '" + exception.getParameterName() + "' is missing."));
    }

    /**
     * =========================================================== Handle Missing
     * Request Header Exception
     * ===========================================================
     *
     * Handles missing HTTP request headers.
     *
     * @param exception Missing request header exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MissingRequestHeaderException.class)
    public ResponseEntity<ApiResponse<Void>> handleMissingRequestHeaderException(
            MissingRequestHeaderException exception) {

        LOGGER.warn("Missing request header : {}", exception.getHeaderName());

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Missing request header.",
                List.of("Required header '" + exception.getHeaderName() + "' is missing."));
    }

    /**
     * =========================================================== Handle Missing
     * Path Variable Exception
     * ===========================================================
     *
     * Handles missing URI path variables.
     *
     * @param exception Missing path variable exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MissingPathVariableException.class)
    public ResponseEntity<ApiResponse<Void>> handleMissingPathVariableException(
            MissingPathVariableException exception) {

        LOGGER.warn("Missing path variable : {}", exception.getVariableName());

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Missing path variable.",
                List.of("Required path variable '" + exception.getVariableName() + "' is missing."));
    }

    /**
     * =========================================================== Handle Method
     * Argument Type Mismatch Exception
     * ===========================================================
     *
     * Handles invalid path variable or request parameter types.
     *
     * @param exception Method argument type mismatch exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
    public ResponseEntity<ApiResponse<Void>> handleMethodArgumentTypeMismatchException(
            MethodArgumentTypeMismatchException exception) {

        LOGGER.warn("Method argument type mismatch : {}", exception.getMessage());

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Invalid request parameter.",
                List.of("Invalid value for parameter '" + exception.getName() + "'."));
    }

    /**
     * =========================================================== Handle HTTP
     * Request Method Not Supported Exception
     * ===========================================================
     *
     * Handles unsupported HTTP methods.
     *
     * @param exception HTTP request method not supported exception
     *
     * @return HTTP 405 Method Not Allowed response
     */
    @ExceptionHandler(HttpRequestMethodNotSupportedException.class)
    public ResponseEntity<ApiResponse<Void>> handleHttpRequestMethodNotSupportedException(
            HttpRequestMethodNotSupportedException exception) {

        LOGGER.warn("HTTP method not supported : {}", exception.getMethod());

        return ApiResponseBuilder.methodNotAllowed(ErrorCodeConstants.FM_COM_001 , "HTTP method '" + exception.getMethod() + "' is not supported.");
    }

    /**
     * =========================================================== Handle No Handler
     * Found Exception ===========================================================
     *
     * Handles requests for non-existing endpoints.
     *
     * @param exception No handler found exception
     *
     * @return HTTP 404 Not Found response
     */
    @ExceptionHandler(NoHandlerFoundException.class)
    public ResponseEntity<ApiResponse<Void>> handleNoHandlerFoundException(NoHandlerFoundException exception) {

        LOGGER.warn("No handler found : {} {}", exception.getHttpMethod(), exception.getRequestURL());

        return ApiResponseBuilder.notFound(ErrorCodeConstants.FM_COM_005 , "Requested API endpoint was not found.");
    }

    // ===========================================================
    // Database Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Data
     * Integrity Violation Exception
     * ===========================================================
     *
     * Handles database integrity constraint violations such as duplicate records
     * and invalid references.
     *
     * @param exception Data integrity violation exception
     *
     * @return HTTP 409 Conflict response
     */
    @ExceptionHandler(DataIntegrityViolationException.class)
    public ResponseEntity<ApiResponse<Void>> handleDataIntegrityViolationException(
            DataIntegrityViolationException exception) {

        LOGGER.error("Database integrity violation.", exception);

        return ApiResponseBuilder.conflict(ErrorCodeConstants.FM_COM_004 , "Database integrity violation.");
    }

    /**
     * =========================================================== Handle Mongo
     * Exception ===========================================================
     *
     * Handles MongoDB related exceptions.
     *
     * @param exception Mongo exception
     *
     * @return HTTP 500 Internal Server Error response
     */
    @ExceptionHandler(MongoException.class)
    public ResponseEntity<ApiResponse<Void>> handleMongoException(MongoException exception) {

        LOGGER.error("MongoDB exception occurred.", exception);

        return ApiResponseBuilder.internalServerError(ErrorCodeConstants.FM_COM_005 , "Database operation failed.");
    }

    // ===========================================================
    // File Upload Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Maximum
     * Upload Size Exceeded Exception
     * ===========================================================
     *
     * Handles requests where uploaded file exceeds the configured maximum upload
     * size.
     *
     * @param exception Maximum upload size exceeded exception
     *
     * @return HTTP 413 Payload Too Large response
     */
    @ExceptionHandler(MaxUploadSizeExceededException.class)
    public ResponseEntity<ApiResponse<Void>> handleMaxUploadSizeExceededException(
            MaxUploadSizeExceededException exception) {

        LOGGER.warn("Maximum upload size exceeded.", exception);

        return ApiResponseBuilder.payloadTooLarge(ErrorCodeConstants.FM_COM_001 , "Uploaded file exceeds maximum allowed size.");
    }

    /**
     * =========================================================== Handle Multipart
     * Exception ===========================================================
     *
     * Handles multipart request processing failures.
     *
     * @param exception Multipart exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MultipartException.class)
    public ResponseEntity<ApiResponse<Void>> handleMultipartException(MultipartException exception) {

        LOGGER.warn("Multipart request failed.", exception);

        return ApiResponseBuilder.badRequest(HttpStatusCode.getDescription(400), "Invalid multipart request.",
                List.of(exception.getMessage()));
    }

    // ===========================================================
    // System Exceptions
    // ===========================================================

    /**
     * Handle IO Exception.
     */
    @ExceptionHandler(IOException.class)
    public ResponseEntity<ApiResponse<Void>> handleIOException(IOException exception) {

        LOGGER.error("IO exception occurred.", exception);

        return ApiResponseBuilder.internalServerError(ErrorCodeConstants.FM_COM_005 , "Unable to process the request.");
    }

    /**
     * Handle Null Pointer Exception.
     */
    @ExceptionHandler(NullPointerException.class)
    public ResponseEntity<ApiResponse<Void>> handleNullPointerException(NullPointerException exception) {

        LOGGER.error("Null pointer exception occurred.", exception);

        return ApiResponseBuilder.internalServerError(ErrorCodeConstants.FM_COM_005 , "Unexpected system error.");
    }

    // ===========================================================
    // Fallback Exception
    // ===========================================================

    /**
     * =========================================================== Handle Unhandled
     * Exceptions ===========================================================
     *
     * Catches any exception that is not explicitly handled by another exception
     * handler.
     *
     * @param exception Unhandled exception
     *
     * @return HTTP 500 Internal Server Error response
     */
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiResponse<Void>> handleException(Exception exception) {

        LOGGER.error("Unhandled exception occurred.", exception);

        return ApiResponseBuilder.internalServerError(ErrorCodeConstants.FM_COM_005 , "An unexpected error occurred. Please contact support.");
    }

}