package com.foodies.freshmeal.common.exception;

import java.io.IOException;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.HttpMessageNotReadableException;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.AuthenticationException;
import org.springframework.web.HttpRequestMethodNotSupportedException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.MissingPathVariableException;
import org.springframework.web.bind.MissingRequestHeaderException;
import org.springframework.web.bind.MissingServletRequestParameterException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException;
import org.springframework.web.multipart.MaxUploadSizeExceededException;
import org.springframework.web.multipart.MultipartException;
import org.springframework.web.servlet.NoHandlerFoundException;
import org.springframework.web.servlet.resource.NoResourceFoundException;

import com.foodies.freshmeal.common.builder.ApiResponseBuilder;
import com.foodies.freshmeal.common.dto.ApiResponse;
import com.mongodb.MongoException;

import jakarta.validation.ConstraintViolationException;

/**
 * ===========================================================
 * Global Exception Handler
 * ===========================================================
 *
 * <p>
 * Centralized exception handling component responsible for converting
 * application, framework and system exceptions into a consistent
 * {@link com.foodies.freshmeal.common.dto.ApiResponse}.
 * </p>
 *
 * <p>
 * Responsibilities:
 * <ul>
 * <li>Handle business exceptions.</li>
 * <li>Handle validation failures.</li>
 * <li>Handle request parsing errors.</li>
 * <li>Handle authentication and authorization errors.</li>
 * <li>Handle file upload exceptions.</li>
 * <li>Handle database exceptions.</li>
 * <li>Handle unexpected system exceptions.</li>
 * </ul>
 * </p>
 *
 * <p>
 * Every exception is logged before an appropriate response is returned to the
 * client.
 * </p>
 *
 * @author Pankaj
 * @since 1.0
 */
@RestControllerAdvice
public class GlobalExceptionHandler {

    /**
     * Logger.
     */
    private static final Logger LOGGER = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    // ===========================================================
    // Validation Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Business
     * Validation Exception
     * ===========================================================
     *
     * <p>
     * Handles validation failures generated by application validators.
     * </p>
     *
     * @param exception Validation exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(ValidationException.class)
    public ResponseEntity<ApiResponse<Void>> handleValidationException(
            ValidationException exception) {

        LOGGER.warn(
                "Validation failed [{}] : {}",
                exception.getErrorCode(),
                exception.getErrorMessage());

        List<String> errors = exception.getValidationResult()
                .getErrors()
                .stream()
                .map(error -> error.getMessage())
                .toList();

        return ApiResponseBuilder.buildResponse(
                exception.getHttpStatusCode(),
                exception.getErrorCode(),
                exception.getErrorMessage(),
                errors);
    }

    /**
     * =========================================================== Handle Method
     * Argument Validation Exception
     * ===========================================================
     *
     * Handles Bean Validation (@Valid) failures.
     *
     * @param exception Validation exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiResponse<Void>> handleMethodArgumentNotValidException(
            final MethodArgumentNotValidException exception) {

        LOGGER.warn("Bean validation failed.");

        List<String> errors = exception.getBindingResult()
                .getFieldErrors()
                .stream()
                .map(fieldError -> fieldError.getDefaultMessage())
                .toList();

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.VALIDATION_FAILED.getHttpStatusCode(),
                CommonErrorConstants.VALIDATION_FAILED.getErrorCode(),
                CommonErrorConstants.VALIDATION_FAILED.getErrorMessage(),
                errors);
    }

    /**
     * =========================================================== Handle Constraint
     * Violation Exception
     * ===========================================================
     *
     * Handles validation failures for path variables and request parameters.
     *
     * @param exception Constraint violation exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(ConstraintViolationException.class)
    public ResponseEntity<ApiResponse<Void>> handleConstraintViolationException(
            final ConstraintViolationException exception) {

        LOGGER.warn("Constraint validation failed.");

        List<String> errors = exception.getConstraintViolations()
                .stream()
                .map(constraintViolation -> constraintViolation.getMessage())
                .toList();

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.VALIDATION_FAILED,
                errors);
    }

    // ===========================================================
    // Business Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Business
     * Exception ===========================================================
     *
     * Handles generic business rule violations.
     *
     * @param exception Business exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(BusinessException.class)
    public ResponseEntity<ApiResponse<Object>> handleBusinessException(
            BusinessException exception) {

        return ApiResponseBuilder.buildResponse(
                exception.getError().getHttpStatusCode(),
                exception.getError().getErrorCode(),
                exception.getError().getErrorMessage());
    }

    /**
     * =========================================================== Handle Illegal
     * Argument Exception
     * ===========================================================
     *
     * Handles invalid method arguments.
     *
     * @param exception Illegal argument exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ApiResponse<Void>> handleIllegalArgumentException(
            final IllegalArgumentException exception) {

        LOGGER.warn("Illegal argument : {}", exception.getMessage());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_REQUEST,
                List.of(CommonErrorConstants.INVALID_REQUEST.getErrorMessage()));
    }

    /**
     * =========================================================== Handle Illegal
     * State Exception ===========================================================
     *
     * Handles invalid application state.
     *
     * @param exception Illegal state exception
     *
     * @return HTTP 409 Conflict response
     */
    @ExceptionHandler(IllegalStateException.class)
    public ResponseEntity<ApiResponse<Void>> handleIllegalStateException(
            final IllegalStateException exception) {

        LOGGER.warn("Illegal state : {}", exception.getMessage());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.OPERATION_FAILED,
                List.of(exception.getMessage()));
    }

    // ===========================================================
    // Authentication & Authorization Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Spring
     * Access Denied Exception
     * ===========================================================
     *
     * Handles authorization failures generated by Spring Security.
     *
     * @param exception Access denied exception
     *
     * @return HTTP 403 Forbidden response
     */
    @ExceptionHandler(AccessDeniedException.class)
    public ResponseEntity<ApiResponse<Void>> handleAccessDeniedException(
            final AccessDeniedException exception) {

        LOGGER.warn("Spring Security access denied : {}", exception.getMessage());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.ACCESS_DENIED);
    }

    /**
     * =========================================================== Handle Spring
     * Authentication Exception
     * ===========================================================
     *
     * Handles authentication failures generated by Spring Security.
     *
     * @param exception Authentication exception
     *
     * @return HTTP 401 Unauthorized response
     */
    @ExceptionHandler(AuthenticationException.class)
    public ResponseEntity<ApiResponse<Void>> handleAuthenticationException(
            final AuthenticationException exception) {

        LOGGER.warn("Authentication failed : {}", exception.getMessage());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.UNAUTHORIZED);
    }

    // ===========================================================
    // Request Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle
     * HttpMessageNotReadableException
     * ===========================================================
     *
     * Handles malformed JSON requests, invalid enum values, invalid date formats
     * and unreadable request bodies.
     *
     * @param exception HTTP message not readable exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(HttpMessageNotReadableException.class)
    public ResponseEntity<ApiResponse<Void>> handleHttpMessageNotReadableException(
            final HttpMessageNotReadableException exception) {

        LOGGER.warn("Malformed request body : {}", exception.getMessage());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_REQUEST,
                List.of("Request body is malformed or contains invalid values."));
    }

    /**
     * =========================================================== Handle Missing
     * Request Parameter Exception
     * ===========================================================
     *
     * Handles missing query parameters.
     *
     * @param exception Missing request parameter exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MissingServletRequestParameterException.class)
    public ResponseEntity<ApiResponse<Void>> handleMissingServletRequestParameterException(
            final MissingServletRequestParameterException exception) {

        LOGGER.warn("Missing request parameter : {}", exception.getParameterName());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_REQUEST,
                List.of("Required parameter '" + exception.getParameterName() + "' is missing."));
    }

    /**
     * =========================================================== Handle Missing
     * Request Header Exception
     * ===========================================================
     *
     * Handles missing HTTP request headers.
     *
     * @param exception Missing request header exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MissingRequestHeaderException.class)
    public ResponseEntity<ApiResponse<Void>> handleMissingRequestHeaderException(
            final MissingRequestHeaderException exception) {

        LOGGER.warn("Missing request header : {}", exception.getHeaderName());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_REQUEST,
                List.of("Required header '" + exception.getHeaderName() + "' is missing."));
    }

    /**
     * =========================================================== Handle Missing
     * Path Variable Exception
     * ===========================================================
     *
     * Handles missing URI path variables.
     *
     * @param exception Missing path variable exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MissingPathVariableException.class)
    public ResponseEntity<ApiResponse<Void>> handleMissingPathVariableException(
            final MissingPathVariableException exception) {

        LOGGER.warn("Missing path variable : {}", exception.getVariableName());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_REQUEST,
                List.of("Required path variable '" + exception.getVariableName() + "' is missing."));
    }

    /**
     * =========================================================== Handle Method
     * Argument Type Mismatch Exception
     * ===========================================================
     *
     * Handles invalid path variable or request parameter types.
     *
     * @param exception Method argument type mismatch exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
    public ResponseEntity<ApiResponse<Void>> handleMethodArgumentTypeMismatchException(
            final MethodArgumentTypeMismatchException exception) {

        LOGGER.warn("Method argument type mismatch : {}", exception.getMessage());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_REQUEST,
                List.of("Invalid value for parameter '" + exception.getName() + "'."));
    }

    /**
     * =========================================================== Handle HTTP
     * Request Method Not Supported Exception
     * ===========================================================
     *
     * Handles unsupported HTTP methods.
     *
     * @param exception HTTP request method not supported exception
     *
     * @return HTTP 405 Method Not Allowed response
     */
    @ExceptionHandler(HttpRequestMethodNotSupportedException.class)
    public ResponseEntity<ApiResponse<Void>> handleHttpRequestMethodNotSupportedException(
            final HttpRequestMethodNotSupportedException exception) {

        LOGGER.warn("HTTP method not supported : {}", exception.getMethod());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_REQUEST,
                List.of("HTTP method '" + exception.getMethod() + "' is not supported."));
    }

    /**
     * =========================================================== Handle No Handler
     * Found Exception ===========================================================
     *
     * Handles requests for non-existing endpoints.
     *
     * @param exception No handler found exception
     *
     * @return HTTP 404 Not Found response
     */
    @ExceptionHandler(NoHandlerFoundException.class)
    public ResponseEntity<ApiResponse<Void>> handleNoHandlerFoundException(
            final NoHandlerFoundException exception) {

        LOGGER.warn("No handler found : {} {}", exception.getHttpMethod(), exception.getRequestURL());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.RESOURCE_NOT_FOUND,
                List.of("Requested API endpoint was not found."));
    }

    // ===========================================================
    // Database Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Data
     * Integrity Violation Exception
     * ===========================================================
     *
     * Handles database integrity constraint violations such as duplicate records
     * and invalid references.
     *
     * @param exception Data integrity violation exception
     *
     * @return HTTP 409 Conflict response
     */
    @ExceptionHandler(DataIntegrityViolationException.class)
    public ResponseEntity<ApiResponse<Void>> handleDataIntegrityViolationException(
            final DataIntegrityViolationException exception) {

        LOGGER.error("Database integrity violation.", exception);

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.DUPLICATE_RESOURCE,
                List.of("Database integrity violation."));
    }

    /**
     * =========================================================== Handle Mongo
     * Exception ===========================================================
     *
     * Handles MongoDB related exceptions.
     *
     * @param exception Mongo exception
     *
     * @return HTTP 500 Internal Server Error response
     */
    @ExceptionHandler(MongoException.class)
    public ResponseEntity<ApiResponse<Void>> handleMongoException(
            final MongoException exception) {

        LOGGER.error("MongoDB exception occurred.", exception);

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.DATABASE_ERROR);
    }

    // ===========================================================
    // File Upload Exceptions
    // ===========================================================

    /**
     * =========================================================== Handle Maximum
     * Upload Size Exceeded Exception
     * ===========================================================
     *
     * Handles requests where uploaded file exceeds the configured maximum upload
     * size.
     *
     * @param exception Maximum upload size exceeded exception
     *
     * @return HTTP 413 Payload Too Large response
     */
    @ExceptionHandler(MaxUploadSizeExceededException.class)
    public ResponseEntity<ApiResponse<Void>> handleMaxUploadSizeExceededException(
            final MaxUploadSizeExceededException exception) {

        LOGGER.warn("Maximum upload size exceeded.", exception);

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.FILE_SIZE_EXCEEDED,
                List.of("Uploaded file exceeds maximum allowed size."));
    }

    /**
     * =========================================================== Handle Multipart
     * Exception ===========================================================
     *
     * Handles multipart request processing failures.
     *
     * @param exception Multipart exception
     *
     * @return HTTP 400 Bad Request response
     */
    @ExceptionHandler(MultipartException.class)
    public ResponseEntity<ApiResponse<Void>> handleMultipartException(
            final MultipartException exception) {

        LOGGER.warn("Multipart request failed.", exception);

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INVALID_FILE,
                List.of("Invalid multipart request."));
    }

    // ===========================================================
    // System Exceptions
    // ===========================================================

    /**
     * Handle IO Exception.
     */
    @ExceptionHandler(IOException.class)
    public ResponseEntity<ApiResponse<Void>> handleIOException(
            final IOException exception) {

        LOGGER.error("IO exception occurred.", exception);

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INTERNAL_SERVER_ERROR,
                List.of("Unable to process the request."));
    }

    /**
     * Handle Null Pointer Exception.
     */
    @ExceptionHandler(NullPointerException.class)
    public ResponseEntity<ApiResponse<Void>> handleNullPointerException(
            final NullPointerException exception) {

        LOGGER.error("Null pointer exception occurred.", exception);

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.INTERNAL_SERVER_ERROR,
                List.of("Unexpected system error."));
    }
    /*
     * handle requested url not found
     */
    @ExceptionHandler(NoResourceFoundException.class)
    public ResponseEntity<ApiResponse<Void>> handleNoResourceFoundException(
            NoResourceFoundException exception) {

        LOGGER.warn("No resource found: {}", exception.getResourcePath());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.URL_UNAVAILABLE,
                List.of("Requested url was not found.", "Requested URL : " + exception.getResourcePath()));
    }

    /**
     * handle no resource found exception
     * 
     * @param exception
     * @return
     */
    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<ApiResponse<Void>> handleResourceFoundException(
            final ResourceNotFoundException exception) {

        LOGGER.warn("Resource not found : {}", exception.getMessage());

        return ApiResponseBuilder.buildResponse(
                CommonErrorConstants.RESOURCE_NOT_FOUND,
                List.of("Requested resource was not found."));
    }

    // ===========================================================
    // Fallback Exception
    // ===========================================================

    /**
     * =========================================================== Handle Unhandled
     * Exceptions ===========================================================
     *
     * Catches any exception that is not explicitly handled by another exception
     * handler.
     *
     * @param exception Unhandled exception
     *
     * @return HTTP 500 Internal Server Error response
     */

    @ExceptionHandler(AbstractBusinessException.class)
    public ResponseEntity<ResponseEntity<ApiResponse<Object>>> handleBusinessException(
            AbstractBusinessException exception) {

        LOGGER.warn(
                "Business Exception [{}] : {}",
                exception.getErrorCode(),
                exception.getErrorMessage());

        return ResponseEntity
                .status(
                        exception.getHttpStatusCode()
                                .toHttpStatus())
                .body(
                        ApiResponseBuilder.buildResponse(
                                exception.getHttpStatusCode(),
                                exception.getErrorCode(),
                                exception.getErrorMessage()));
    }

}